#ifndef blue_boardevent_hpp
#define blue_boardevent_hpp

namespace blue
{
    class Machine_event;

    //! A board event is an event generated by the board. It is accompanied
    //! by an event context which contains details about the event.
    enum boardevent
    {
        BoardMachineEvent   = 0,
        BoardSecondaryEvent = 1
    };

    typedef const void* boardeventcontext;
}

#endif
